# fly.toml app configuration file generated for climbdex-shy-dawn-4499 on 2024-07-17T17:22:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'climbdex-shy-dawn-4499'
primary_region = 'ams'

[build]
  builder = 'paketobuildpacks/builder:full'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
