# fly.toml app configuration file generated for climbdex on 2023-12-22T16:48:26-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "climbdex"
primary_region = "sjc"

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024